name: Backend Unit Tests

on:
  push:
    branches:
      - main  # Trigger action on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger action when creating a PR to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js version 16 (or whichever version you use)

      - name: Install dependencies
        run: |
          npm install  # Install dependencies defined in your package.json

      - name: Run backend tests
        run: |
          npm test  # Runs your backend unit tests (assuming you're using Jest)
