name: Run Unit Tests

on:
  push:
    branches:
      - main  # Specify which branch to trigger the tests on (e.g., main, dev, feature-branch)
  pull_request:
    branches:
      - main  # Trigger when there's a PR targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # The OS your tests will run on
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your repo so the workflow can run tests on it

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Choose your desired Node.js version

      - name: Install dependencies
        run: |
          npm install  # Install project dependencies

      - name: Run unit tests
        run: |
          npm test  # Run unit tests (e.g., using Jest)
